/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "teal-accent": "#14B8A6",
        "electric-cyan": "#14B8A6",
        "amber-gold": "#64748B",
        "slate-dark": "#1E293B",
        "on-error": "#690005",
        "surface": "#131313",
        "on-tertiary-container": "#006274",
        "inverse-surface": "#e5e2e1",
        "surface-base": "#0F1419",
        "background": "#0F1419",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1c1b1b",
        "secondary-container": "#03c6b2",
        "tertiary-fixed": "#acedff",
        "primary-container": "#6ee7b7",
        "text-muted": "#A3A3A3",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#005047",
        "primary-fixed-dim": "#62dcad",
        "surface-container-highest": "#353534",
        "surface-tint": "#62dcad",
        "border-glass": "rgba(255, 255, 255, 0.08)",
        "error": "#ffb4ab",
        "on-primary-container": "#006649",
        "secondary": "#44e2cd",
        "on-secondary-fixed": "#00201c",
        "on-surface": "#e5e2e1",
        "on-primary": "#003827",
        "secondary-fixed-dim": "#3cddc7",
        "status-success": "#10B981",
        "secondary-fixed": "#62fae3",
        "text-primary": "#FFFFFF",
        "primary-fixed": "#80f9c8",
        "on-tertiary": "#003640",
        "surface-dim": "#131313",
        "on-background": "#e5e2e1",
        "primary": "#aaffd8",
        "on-surface-variant": "#bccac1",
        "on-primary-fixed-variant": "#00513a",
        "surface-elevated": "#181818",
        "status-error": "#EF4444",
        "on-secondary": "#003731",
        "tertiary-fixed-dim": "#4cd7f6",
        "error-container": "#93000a",
        "on-primary-fixed": "#002115",
        "on-secondary-container": "#004d44",
        "outline-variant": "#3d4a43",
        "tertiary": "#cef4ff",
        "on-tertiary-fixed": "#001f26",
        "inverse-on-surface": "#313030",
        "inverse-primary": "#006c4e",
        "outline": "#86948c",
        "on-tertiary-fixed-variant": "#004e5c",
        "tertiary-container": "#63e1ff",
        "surface-bright": "#3a3939",
        "surface-variant": "#353534",
        "surface-container-high": "#2a2a2a",
        "surface-container": "#201f1f"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "gutter": "16px",
        "section-gap": "80px",
        "unit": "8px",
        "container-margin": "24px"
      },
      fontFamily: {
        "body-lg": ["Manrope", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
        "headline-xl": ["Manrope", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "button-text": ["Manrope", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"],
        "label-mono": ["IBM Plex Mono", "monospace"],
        "code": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-xl": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "button-text": ["14px", { "lineHeight": "1.0", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "label-mono": ["13px", { "lineHeight": "1.0", "letterSpacing": "0.05em", "fontWeight": "500" }]
      }
    },
  },
  plugins: [],
};
