/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#cfbcff",
        "tertiary-fixed": "#ffdf93",
        "tertiary-container": "#c9a74d",
        "on-primary-fixed": "#22005d",
        "on-background": "#e6e0e9",
        "secondary": "#cdc0e9",
        "secondary-fixed": "#e9ddff",
        "error": "#ffb4ab",
        "surface-variant": "#36343a",
        "primary-fixed": "#e9ddff",
        "on-surface-variant": "#cbc4d2",
        "on-tertiary": "#3e2e00",
        "secondary-container": "#4d4465",
        "outline": "#948e9c",
        "secondary-fixed-dim": "#cdc0e9",
        "surface-container-low": "#1d1b20",
        "on-secondary-container": "#bfb2da",
        "surface-dim": "#141218",
        "surface": "#141218",
        "surface-container-highest": "#36343a",
        "primary-container": "#6750a4",
        "on-error-container": "#ffdad6",
        "background": "#141218",
        "on-secondary-fixed": "#1f1635",
        "on-primary-fixed-variant": "#4f378a",
        "primary": "#cfbcff",
        "surface-bright": "#3b383e",
        "on-error": "#690005",
        "on-tertiary-container": "#503d00",
        "surface-container-high": "#2b292f",
        "primary-fixed-dim": "#cfbcff",
        "on-tertiary-fixed-variant": "#594400",
        "on-secondary": "#342b4b",
        "outline-variant": "#494551",
        "on-secondary-fixed-variant": "#4b4263",
        "surface-container": "#211f24",
        "inverse-surface": "#e6e0e9",
        "on-tertiary-fixed": "#241a00",
        "on-primary-container": "#e0d2ff",
        "on-primary": "#381e72",
        "tertiary-fixed-dim": "#e7c365",
        "inverse-primary": "#6750a4",
        "tertiary": "#e7c365",
        "error-container": "#93000a",
        "on-surface": "#e6e0e9",
        "surface-container-lowest": "#0f0d13",
        "inverse-on-surface": "#322f35",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
      spacing: {
        "margin-mobile": "16px",
        "container-gap": "12px",
        "unit": "4px",
        "margin-desktop": "32px",
        "gutter": "16px",
      },
      fontFamily: {
        "display-lg": ["var(--font-space-grotesk)"],
        "body-md": ["var(--font-jetbrains-mono)"],
        "body-lg": ["var(--font-jetbrains-mono)"],
        "headline-lg": ["var(--font-space-grotesk)"],
        "data-tabular": ["var(--font-jetbrains-mono)"],
        "label-caps": ["var(--font-jetbrains-mono)"],
        "headline-md": ["var(--font-space-grotesk)"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "data-tabular": ["13px", { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-caps": ["11px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

